name: sda_tuyimbe_web
description: SDA Tuyimbe Hymnal download page built with Jaspr
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  jaspr: ^0.23.0

dev_dependencies:
  jaspr_builder: ^0.23.0
  webdev: ^3.8.1
  build_runner: ^2.4.0
  build_web_compilers: ^4.8.0

jaspr:
  mode: client
